version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: "weekly"
    target-branch: "feat/refresh"
    labels:
      - "ci dependencies"
      - "ci"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/apps/marketing"
    schedule:
      interval: "weekly"
    target-branch: "feat/refresh"
    labels:
      - "npm dependencies"
      - "frontend"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    target-branch: "feat/refresh"
    labels:
      - "npm dependencies"
      - "frontend"
    open-pull-requests-limit: 0
